### ISSUE TITLE
fix up update_packages()

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_package_updater#22]
the intention of this function is to increase the installed package ranges in `packages.yml` 

there is code currently built out to support updating the version range of `fivetran_utils` and _maybe_ source packages (not fully tested). 

let's make this work more consistently and maybe more flexibly (ie update more kinds of package dependencies). perhaps we can provide a dictionary config that can tell the script exactly which package deps to update:
```yml
package-deps-to-change:
- name: dbt-labs/spark_utils
   new_version_range: [">=0.3.0", "<0.4.0"]
- name: calogica/dbt_expectations
  new_version_range: [">=0.8.0", "<0.9.0"]
...
```

instead of hard-coding everything (and limiting ourselves to only updating fivetran package versions) 

Moreover, i think it would be really cool if this function could also update the package dependency matrix in the README
